import re

def validate_ai_output(ai_output: str, live_price=None, live_pe=None):
    """
    Validates or sanitizes the AI output string. 
    Accepts optional live_price and live_pe arguments without crashing if they are omitted.
    """
    if not ai_output:
        return "No output generated by the AI committee."
        
    # Your existing validation/formatting logic here...
    validated_text = ai_output
    
    # Optional check example if prices were passed
    if live_price is not None:
        # you can append or verify details if needed
        pass

    return validated_text