import os
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_pdf_memorandum(ticker, report_text, wacc, growth):
    """Generates a professional corporate PDF investment memorandum in memory."""
    buffer = BytesIO()
    
    # Page setup with standard margins
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=letter,
        rightMargin=40, leftMargin=40, 
        topMargin=40, bottomMargin=40
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Corporate Styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        textColor=colors.HexColor('#1e2530'),
        spaceAfter=6
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        textColor=colors.HexColor('#555555'),
        spaceAfter=15
    )
    
    body_style = ParagraphStyle(
        'DocBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#222222'),
        spaceAfter=10
    )

    story = []

    # Header Section
    story.append(Paragraph(f"Institutional Investment Memorandum: {ticker}", title_style))
    story.append(Paragraph(f"Generated by Multi-Agent AI Equity Committee | Model Settings: WACC={wacc*100}%, Growth={growth*100}%", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#1e2530'), spaceAfter=15))

    # Parse and add report contents paragraph by paragraph
    paragraphs = report_text.split('\n')
    for para in paragraphs:
        if para.strip():
            # Clean markdown bold asterisks if any exist for cleaner PDF text rendering
            clean_text = para.replace('**', '')
            if clean_text.startswith('#'):
                clean_text = clean_text.lstrip('#').strip()
                story.append(Paragraph(f"<b>{clean_text}</b>", body_style))
            else:
                story.append(Paragraph(clean_text, body_style))
        else:
            story.append(Spacer(1, 6))

    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()